Dev
GauravMakhijani/StatusChecker pull request #1
Opened 2023-01-30 05:37 UTC by GauravMakhijani

2023-01-31 07:56 UTC, sushmitaw requested changes

2023-01-31 07:56 UTC, sushmitaw commented on db/website.go
> +	s.DB.Exec("INSERT INTO links (link, status) VALUES ($1, $2)", website.Link, website.Status)
missing error handling

2023-01-31 07:56 UTC, sushmitaw commented on db/website.go
> +	err = s.DB.Select(&ws, "SELECT id,link,status FROM links WHERE link LIKE $1", "%"+query+"%")
log the error

2023-01-31 07:56 UTC, sushmitaw commented on statuschecker/handler.go
> +func handlePostRequest(w http.ResponseWriter, r *http.Request, service Service) {
rename to createWebsiteHandler

2023-01-31 07:56 UTC, sushmitaw commented on statuschecker/handler.go
> +	fmt.Println("Post request successful")
use log info instead of fmt

2023-01-31 07:56 UTC, sushmitaw commented on statuschecker/handler.go
> +func handleGetRequest(w http.ResponseWriter, r *http.Request, service Service) {
rename to getWebsiteHandler

2023-01-31 07:56 UTC, sushmitaw commented on statuschecker/handler.go
> +	query := r.URL.Query().Get("name")
query is wrong variable naming here it should be website or websiteName

2023-01-31 07:56 UTC, sushmitaw commented on statuschecker/handler.go
> +	fmt.Println("Get request successful")
change all fmt to logs

2023-01-31 07:56 UTC, sushmitaw commented on statuschecker/handler.go
> +
use go fmt ./... to format all code

2023-01-31 07:56 UTC, sushmitaw commented on statuschecker/service.go
> +func (s *statusService) Append(ctx context.Context, website db.WebsiteStatus) (err error) {
Append is wrong naming convention use add or create

2023-01-31 07:56 UTC, sushmitaw commented on statuschecker/service.go
> +	s.repo.InsertWebsite(website)
error handling missing

2023-01-31 07:56 UTC, sushmitaw commented on statuschecker/service.go
> +	// s.repo.GetWebsiteStatus(url)
remove commented code if not needed

2023-01-31 07:56 UTC, sushmitaw commented on statuschecker/service.go
> +			fmt.Println("Checking status of websites")
use log

2023-01-31 14:09 UTC, GauravMakhijani commented on db/website.go
> +	s.DB.Exec("INSERT INTO links (link, status) VALUES ($1, $2)", website.Link, website.Status)
Done!

2023-02-02 06:56 UTC, sushmitaw approved these changes

2023-02-02 06:56 UTC, merged